version: '3'

networks:
  default:
    external:
      name: test_default

services:
  selenium_tester:
    #image: markadams/chromium-xvfb-py2:latest
    build:
      context: ./tester_docker
    volumes:
      - ./:/opt/work
    external_links:
      - backlogs_redmine_1:redmine

  mechanize_tester:
    build:
      context: ./mechanize
    volumes:
      - ./mechanize:/opt/work

